### ISSUE TITLE
test file error in process.py

### ISSUE THREAD

**Issue by dubing-bit** [NorthStarUAS/ImageAnalysis#28]
Hi, I don't know if you still maintain this project? I'm running scripts/process.py and the test file and the error comes up and I don't know what's wrong.
**`(ImageAnalysis) dubing@dubingUbuntu:~/code/ImageAnalysis/scripts$ python3 process.py  /home/dubing/data/sprc-20190111/images/

Project processed on host: dubingUbuntu

Project processed with arguments: Namespace(cam_calibration=False, camera=None, detector='SIFT', filter='gms', force_altitude=None, grid_detect=1, ground=None, group=0, match_ratio=0.75, match_strategy='traditional', max_angle=25.0, max_dist=None, min_chain_length=3, min_dist=None, min_pairs=25, orb_max_features=20000, pitch_deg=-90.0, project='/home/dubing/data/sprc-20190111/images/', refine=False, reject_margin=0, roll_deg=0.0, scale=0.4, star_line_threshold_binarized=8, star_line_threshold_projected=10, star_max_size=16, star_response_threshold=30, star_suppress_nonmax_size=5, surf_hessian_threshold=600, surf_noctaves=4, yaw_deg=0.0)

Step 1: setup the project

Creating analysis directory: /home/dubing/data/sprc-20190111/images/ImageAnalysis

project: creating meta directory: /home/dubing/data/sprc-20190111/images/ImageAnalysis/meta

project: creating cache directory: /home/dubing/data/sprc-20190111/images/ImageAnalysis/cache

project: creating state directory: /home/dubing/data/sprc-20190111/images/ImageAnalysis/state

project: project configuration doesn't exist: /home/dubing/data/sprc-20190111/images/ImageAnalysis/config.json

Continuing with an empty project configuration

Created project: /home/dubing/data/sprc-20190111/images/

Traceback (most recent call last):

  File "process.py", line 131, in <module>

    camera_name, make, model, lens_model = proj.detect_camera()

  File "/home/dubing/code/ImageAnalysis/scripts/lib/project.py", line 139, in detect_camera

    lens_model = lens_model.replace("/", "-")

AttributeError: 'NoneType' object has no attribute 'replace'**

`

**Comment by dubing-bit** [comment]
maybe should comment out
